[project]
name = "PharmacoSet-Pipelines"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jermiah <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64"]

[tasks]

[dependencies]
r-base = ">=4.3.3,<4.4"
radian = ">=0.6.12,<0.7"
r-essentials = ">=4.3,<5"
r-rmarkdown = ">=2.27,<3"
r-qs = ">=0.26.3,<0.27"


[tasks.setup]
cmd = "Rscript scripts/setup.R"
description = "Install R packages and setup the environment"

[tasks.build]
cmd = "Rscript scripts/build.R"
description = "Build the project"
depends-on = ["setup"]

[system-requirements]
linux = "5.4.203"
