[project]
name = "PharmacoSet-Pipelines"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jermiah <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]


[dependencies]
radian = ">=0.6.12,<0.7"
r-base = ">=4.3.3,<4.4"
r-essentials = ">=4.3,<5"
r-rmarkdown = ">=2.27,<3"
r-qs = ">=0.26.3,<0.27"
bioconductor-biocstyle = ">=2.30.0,<2.31"
r-prettydoc = ">=0.4.1,<0.5"

[tasks.setup]
cmd = "Rscript scripts/setup.R"
description = "Install R packages and setup the environment"

[tasks.build]
cmd = "Rscript -e 'rmarkdown::render(`PSet-Update_Logs.rmd`, output_file = `index.html`)'"
description = "Build the project"

[system-requirements]
linux = "5.4.203"
